export const AUTO_COLORS = { currency: '#059669', date: '#0284c7', time: '#ea580c', number: '#7c3aed' };
export const AUTO_COLOR_VALUES = Object.values(AUTO_COLORS);

export const CATEGORIES = {
    'Food': { icon: '🍔', color: '#b45309', bg: '#fef3c7' },       
    'Transport': { icon: '🚕', color: '#1d4ed8', bg: '#dbeafe' },  
    'Travel': { icon: '✈️', color: '#6d28d9', bg: '#ede9fe' },     
    'Fun': { icon: '🎟️', color: '#be185d', bg: '#fce7f3' },    
    'Transfer': { icon: '💸', color: '#047857', bg: '#d1fae5' }, 
    'Other': { icon: '📝', color: '#334155', bg: '#f1f5f9' }       
};

export const COLORS = ['#4f46e5', '#ea580c', '#059669', '#d97706', '#7c3aed', '#db2777', '#0d9488', '#2563eb', '#c026d3', '#0284c7'];

// Dynamic Tag Palette
export const TAG_COLORS = [
    { bg: '#fee2e2', color: '#b91c1c', border: '#fecaca' }, // Red
    { bg: '#ffedd5', color: '#c2410c', border: '#fed7aa' }, // Orange
    { bg: '#fef3c7', color: '#b45309', border: '#fde68a' }, // Amber
    { bg: '#ecfccb', color: '#4d7c0f', border: '#d9f99d' }, // Lime
    { bg: '#dcfce7', color: '#15803d', border: '#bbf7d0' }, // Green
    { bg: '#d1fae5', color: '#047857', border: '#a7f3d0' }, // Emerald
    { bg: '#ccfbf1', color: '#0f766e', border: '#99f6e4' }, // Teal
    { bg: '#cffafe', color: '#0369a1', border: '#5eead4' }, // Cyan
    { bg: '#e0f2fe', color: '#0369a1', border: '#bae6fd' }, // Light Blue
    { bg: '#dbeafe', color: '#1d4ed8', border: '#bfdbfe' }, // Blue
    { bg: '#e0e7ff', color: '#4338ca', border: '#c7d2fe' }, // Indigo
    { bg: '#ede9fe', color: '#6d28d9', border: '#ddd6fe' }, // Violet
    { bg: '#f3e8ff', color: '#7e22ce', border: '#e9d5ff' }, // Purple
    { bg: '#fae8ff', color: '#a21caf', border: '#f3ccff' }, // Fuchsia
    { bg: '#fce7f3', color: '#be185d', border: '#fbcfe8' }, // Pink
    { bg: '#ffe4e6', color: '#be123c', border: '#fecdd3' }  // Rose
];

export const CURRENCY_SYMBOLS = { 
    USD: '$', EUR: '€', GBP: '£', CAD: 'C$', AUD: 'A$', JPY: '¥', CHF: 'Fr', MXN: 'M$', 
    INR: '₹', BRL: 'R$', KRW: '₩', CNY: '¥', HKD: 'HK$', SGD: 'S$', NOK: 'kr', SEK: 'kr', 
    DKK: 'kr', NZD: 'NZ$', ZAR: 'R', AED: 'د.إ', THB: '฿', TRY: '₺', PLN: 'zł', CZK: 'Kč', 
    HUF: 'Ft', PHP: '₱', IDR: 'Rp', MYR: 'RM', CLP: 'CLP$', COP: 'COL$', ILS: '₪',
    ARS: '$', VND: '₫', EGP: 'E£', SAR: '﷼', TWD: 'NT$', PEN: 'S/', CRC: '₡', UAH: '₴',
    QAR: 'QR', KWD: 'KD', BHD: 'BD', OMR: 'OMR', JOD: 'JD', DZD: 'DA', MAD: 'MAD', TND: 'DT',
    NGN: '₦', KES: 'KSh', GHS: 'GH₵', TZS: 'TSh', UGX: 'USh', ETB: 'Br', BWP: 'P', NAD: 'N$',
    MUR: '₨', ZMW: 'ZK', BND: 'B$', KHR: '៛', LAK: '₭', MMK: 'K', NPR: '₨', PKR: '₨',
    LKR: 'Rs', BDT: '৳', MNT: '₮', GEL: '₾', AMD: '֏', AZN: '₼', KZT: '₸', UZS: "so'm",
    BYN: 'Br', MDL: 'L', RSD: 'din', BAM: 'KM', MKD: 'den', ALL: 'L', ISK: 'kr', BGN: 'лв',
    RON: 'lei', DOP: 'RD$', JMD: 'J$', TTD: 'TT$', BSD: 'B$', BBD: 'Bds$', BZD: 'BZ$',
    GYD: 'G$', HTG: 'G', PAB: 'B/.', NIO: 'C$', HNL: 'L', GTQ: 'Q', PYG: '₲', BOB: 'Bs',
    UYU: '$U', FJD: 'FJ$', PGK: 'K', WST: 'WS$', VUV: 'VT', XAF: 'FCFA', XOF: 'CFA',
    XPF: '₣', ANG: 'NAƒ', AWG: 'Afl', BMD: 'BD$', KYD: 'CI$', MOP: 'MOP$', MVR: 'Rf',
    SCR: 'SR', SZL: 'L', LSL: 'L', MWK: 'MK', CDF: 'FC', AOA: 'Kz', CVE: 'Esc', DJF: 'Fdj',
    GNF: 'FG', KMF: 'CF', LRD: 'L$', MGA: 'Ar', MRU: 'UM', RWF: 'FRw', STN: 'Db', SOS: 'Sh',
    SLL: 'Le', SSP: 'SS£', SDG: 'SDG', SYP: 'LS', IQD: 'ID', YER: 'YR', AFN: '؋', TJS: 'SM',
    TMT: 'T', BTN: 'Nu.', TOP: 'T$', SBD: 'SI$', CUC: 'CUC$', CUP: '$MN', GIP: '£', FKP: '£',
    BIF: 'FBu', ERN: 'Nfk', GMD: 'D', HRK: 'kn', IRR: '﷼', KGS: 'с', KPW: '₩', LBP: 'L£',
    LYD: 'LD', MZN: 'MT', RUB: '₽'
};

export const COMMON_CURRENCIES = [
    { code: 'EUR', flag: '🇪🇺', name: 'Euro' },
    { code: 'GBP', flag: '🇬🇧', name: 'British Pound' },
    { code: 'CAD', flag: '🇨🇦', name: 'Canadian Dollar' },
    { code: 'AUD', flag: '🇦🇺', name: 'Australian Dollar' },
    { code: 'JPY', flag: '🇯🇵', name: 'Japanese Yen' },
    { code: 'CHF', flag: '🇨🇭', name: 'Swiss Franc' },
    { code: 'MXN', flag: '🇲🇽', name: 'Mexican Peso' },
    { code: 'INR', flag: '🇮🇳', name: 'Indian Rupee' },
    { code: 'BRL', flag: '🇧🇷', name: 'Brazilian Real' },
    { code: 'KRW', flag: '🇰🇷', name: 'South Korean Won' },
    { code: 'CNY', flag: '🇨🇳', name: 'Chinese Yuan' },
    { code: 'HKD', flag: '🇭🇰', name: 'Hong Kong Dollar' },
    { code: 'SGD', flag: '🇸🇬', name: 'Singapore Dollar' },
    { code: 'NOK', flag: '🇳🇴', name: 'Norwegian Krone' },
    { code: 'SEK', flag: '🇸🇪', name: 'Swedish Krona' },
    { code: 'DKK', flag: '🇩🇰', name: 'Danish Krone' },
    { code: 'NZD', flag: '🇳🇿', name: 'New Zealand Dollar' },
    { code: 'ZAR', flag: '🇿🇦', name: 'South African Rand' },
    { code: 'AED', flag: '🇦🇪', name: 'UAE Dirham' },
    { code: 'THB', flag: '🇹🇭', name: 'Thai Baht' },
    { code: 'TRY', flag: '🇹🇷', name: 'Turkish Lira' },
    { code: 'PLN', flag: '🇵🇱', name: 'Polish Zloty' },
    { code: 'CZK', flag: '🇨🇿', name: 'Czech Koruna' },
    { code: 'HUF', flag: '🇭🇺', name: 'Hungarian Forint' },
    { code: 'PHP', flag: '🇵🇭', name: 'Philippine Peso' },
    { code: 'IDR', flag: '🇮🇩', name: 'Indonesian Rupiah' },
    { code: 'MYR', flag: '🇲🇾', name: 'Malaysian Ringgit' },
    { code: 'CLP', flag: '🇨🇱', name: 'Chilean Peso' },
    { code: 'COP', flag: '🇨🇴', name: 'Colombian Peso' },
    { code: 'ILS', flag: '🇮🇱', name: 'Israeli New Shekel' }
];

export const ALL_CURRENCIES = [
    { code: 'USD', flag: '🇺🇸', name: 'US Dollar' },
    { code: 'EUR', flag: '🇪🇺', name: 'Euro' },
    { code: 'GBP', flag: '🇬🇧', name: 'British Pound' },
    { code: 'CAD', flag: '🇨🇦', name: 'Canadian Dollar' },
    { code: 'AUD', flag: '🇦🇺', name: 'Australian Dollar' },
    { code: 'JPY', flag: '🇯🇵', name: 'Japanese Yen' },
    { code: 'CHF', flag: '🇨🇭', name: 'Swiss Franc' },
    { code: 'CNY', flag: '🇨🇳', name: 'Chinese Yuan' },
    { code: 'INR', flag: '🇮🇳', name: 'Indian Rupee' },
    { code: 'BRL', flag: '🇧🇷', name: 'Brazilian Real' },
    { code: 'MXN', flag: '🇲🇽', name: 'Mexican Peso' },
    { code: 'KRW', flag: '🇰🇷', name: 'South Korean Won' },
    { code: 'HKD', flag: '🇭🇰', name: 'Hong Kong Dollar' },
    { code: 'SGD', flag: '🇸🇬', name: 'Singapore Dollar' },
    { code: 'NOK', flag: '🇳🇴', name: 'Norwegian Krone' },
    { code: 'SEK', flag: '🇸🇪', name: 'Swedish Krona' },
    { code: 'DKK', flag: '🇩🇰', name: 'Danish Krone' },
    { code: 'NZD', flag: '🇳🇿', name: 'New Zealand Dollar' },
    { code: 'ZAR', flag: '🇿🇦', name: 'South African Rand' },
    { code: 'AED', flag: '🇦🇪', name: 'UAE Dirham' },
    { code: 'THB', flag: '🇹🇭', name: 'Thai Baht' },
    { code: 'TRY', flag: '🇹🇷', name: 'Turkish Lira' },
    { code: 'PLN', flag: '🇵🇱', name: 'Polish Zloty' },
    { code: 'CZK', flag: '🇨🇿', name: 'Czech Koruna' },
    { code: 'HUF', flag: '🇭🇺', name: 'Hungarian Forint' },
    { code: 'PHP', flag: '🇵🇭', name: 'Philippine Peso' },
    { code: 'IDR', flag: '🇮🇩', name: 'Indonesian Rupiah' },
    { code: 'MYR', flag: '🇲🇾', name: 'Malaysian Ringgit' },
    { code: 'CLP', flag: '🇨🇱', name: 'Chilean Peso' },
    { code: 'COP', flag: '🇨🇴', name: 'Colombian Peso' },
    { code: 'ILS', flag: '🇮🇱', name: 'Israeli New Shekel' },
    { code: 'ARS', flag: '🇦🇷', name: 'Argentine Peso' },
    { code: 'VND', flag: '🇻🇳', name: 'Vietnamese Dong' },
    { code: 'EGP', flag: '🇪🇬', name: 'Egyptian Pound' },
    { code: 'SAR', flag: '🇸🇦', name: 'Saudi Riyal' },
    { code: 'TWD', flag: '🇹🇼', name: 'New Taiwan Dollar' },
    { code: 'PEN', flag: '🇵🇪', name: 'Peruvian Sol' },
    { code: 'CRC', flag: '🇨🇷', name: 'Costa Rican Colón' },
    { code: 'UAH', flag: '🇺🇦', name: 'Ukrainian Hryvnia' },
    { code: 'QAR', flag: '🇶🇦', name: 'Qatari Riyal' },
    { code: 'KWD', flag: '🇰🇼', name: 'Kuwaiti Dinar' },
    { code: 'BHD', flag: '🇧🇭', name: 'Bahraini Dinar' },
    { code: 'OMR', flag: '🇴🇲', name: 'Omani Rial' },
    { code: 'JOD', flag: '🇯🇴', name: 'Jordanian Dinar' },
    { code: 'DZD', flag: '🇩🇿', name: 'Algerian Dinar' },
    { code: 'MAD', flag: '🇲🇦', name: 'Moroccan Dirham' },
    { code: 'TND', flag: '🇹🇳', name: 'Tunisian Dinar' },
    { code: 'NGN', flag: '🇳🇬', name: 'Nigerian Naira' },
    { code: 'KES', flag: '🇰🇪', name: 'Kenyan Shilling' },
    { code: 'GHS', flag: '🇬🇭', name: 'Ghanaian Cedi' },
    { code: 'TZS', flag: '🇹🇿', name: 'Tanzanian Shilling' },
    { code: 'UGX', flag: '🇺🇬', name: 'Ugandan Shilling' },
    { code: 'ETB', flag: '🇪🇹', name: 'Ethiopian Birr' },
    { code: 'BWP', flag: '🇧🇼', name: 'Botswanan Pula' },
    { code: 'NAD', flag: '🇳🇦', name: 'Namibian Dollar' },
    { code: 'MUR', flag: '🇲🇺', name: 'Mauritian Rupee' },
    { code: 'ZMW', flag: '🇿🇲', name: 'Zambian Kwacha' },
    { code: 'BND', flag: '🇧🇳', name: 'Brunei Dollar' },
    { code: 'KHR', flag: '🇰🇭', name: 'Cambodian Riel' },
    { code: 'LAK', flag: '🇱🇦', name: 'Lao Kip' },
    { code: 'MMK', flag: '🇲🇲', name: 'Myanmar Kyat' },
    { code: 'NPR', flag: '🇳🇵', name: 'Nepalese Rupee' },
    { code: 'PKR', flag: '🇵🇰', name: 'Pakistani Rupee' },
    { code: 'LKR', flag: '🇱🇰', name: 'Sri Lankan Rupee' },
    { code: 'BDT', flag: '🇧🇩', name: 'Bangladeshi Taka' },
    { code: 'MNT', flag: '🇲🇳', name: 'Mongolian Tugrik' },
    { code: 'GEL', flag: '🇬🇪', name: 'Georgian Lari' },
    { code: 'AMD', flag: '🇦🇲', name: 'Armenian Dram' },
    { code: 'AZN', flag: '🇦🇿', name: 'Azerbaijani Manat' },
    { code: 'KZT', flag: '🇰🇿', name: 'Kazakhstani Tenge' },
    { code: 'UZS', flag: '🇺🇿', name: 'Uzbekistani Som' },
    { code: 'BYN', flag: '🇧🇾', name: 'Belarusian Ruble' },
    { code: 'MDL', flag: '🇲🇩', name: 'Moldovan Leu' },
    { code: 'RSD', flag: '🇷🇸', name: 'Serbian Dinar' },
    { code: 'BAM', flag: '🇧🇦', name: 'Bosnia-Herzegovina Mark' },
    { code: 'MKD', flag: '🇲🇰', name: 'Macedonian Denar' },
    { code: 'ALL', flag: '🇦🇱', name: 'Albanian Lek' },
    { code: 'ISK', flag: '🇮🇸', name: 'Icelandic Krona' },
    { code: 'BGN', flag: '🇧🇬', name: 'Bulgarian Lev' },
    { code: 'RON', flag: '🇷🇴', name: 'Romanian Leu' },
    { code: 'DOP', flag: '🇩🇴', name: 'Dominican Peso' },
    { code: 'JMD', flag: '🇯🇲', name: 'Jamaican Dollar' },
    { code: 'TTD', flag: '🇹🇹', name: 'Trinidad & Tobago Dollar' },
    { code: 'BSD', flag: '🇧🇸', name: 'Bahamian Dollar' },
    { code: 'BBD', flag: '🇧🇧', name: 'Barbadian Dollar' },
    { code: 'BZD', flag: '🇧🇿', name: 'Belize Dollar' },
    { code: 'GYD', flag: '🇬🇾', name: 'Guyanese Dollar' },
    { code: 'HTG', flag: '🇭🇹', name: 'Haitian Gourde' },
    { code: 'PAB', flag: '🇵🇦', name: 'Panamanian Balboa' },
    { code: 'NIO', flag: '🇳🇮', name: 'Nicaraguan Córdoba' },
    { code: 'HNL', flag: '🇭🇳', name: 'Honduran Lempira' },
    { code: 'GTQ', flag: '🇬🇹', name: 'Guatemalan Quetzal' },
    { code: 'PYG', flag: '🇵🇾', name: 'Paraguayan Guarani' },
    { code: 'BOB', flag: '🇧🇴', name: 'Bolivian Boliviano' },
    { code: 'UYU', flag: '🇺🇾', name: 'Uruguayan Peso' },
    { code: 'FJD', flag: '🇫🇯', name: 'Fijian Dollar' },
    { code: 'PGK', flag: '🇵🇬', name: 'Papua New Guinean Kina' },
    { code: 'WST', flag: '🇼🇸', name: 'Samoan Tala' },
    { code: 'VUV', flag: '🇻🇺', name: 'Vanuatu Vatu' },
    { code: 'XAF', flag: '🇨🇲', name: 'Central African CFA Franc' },
    { code: 'XOF', flag: '🇸🇳', name: 'West African CFA Franc' },
    { code: 'XPF', flag: '🇵🇫', name: 'CFP Franc' },
    { code: 'ANG', flag: '🇨🇼', name: 'Netherlands Antillean Guilder' },
    { code: 'AWG', flag: '🇦🇼', name: 'Aruban Florin' },
    { code: 'BMD', flag: '🇧🇲', name: 'Bermudian Dollar' },
    { code: 'KYD', flag: '🇰🇾', name: 'Cayman Islands Dollar' },
    { code: 'MOP', flag: '🇲🇴', name: 'Macanese Pataca' },
    { code: 'MVR', flag: '🇲🇻', name: 'Maldivian Rufiyaa' },
    { code: 'SCR', flag: '🇸🇨', name: 'Seychellois Rupee' },
    { code: 'SZL', flag: '🇸🇿', name: 'Swazi Lilangeni' },
    { code: 'LSL', flag: '🇱🇸', name: 'Lesotho Loti' },
    { code: 'MWK', flag: '🇲🇼', name: 'Malawian Kwacha' },
    { code: 'CDF', flag: '🇨🇩', name: 'Congolese Franc' },
    { code: 'AOA', flag: '🇦🇴', name: 'Angolan Kwanza' },
    { code: 'CVE', flag: '🇨🇻', name: 'Cape Verdean Escudo' },
    { code: 'DJF', flag: '🇩🇯', name: 'Djiboutian Franc' },
    { code: 'GNF', flag: '🇬🇳', name: 'Guinean Franc' },
    { code: 'KMF', flag: '🇰🇲', name: 'Comorian Franc' },
    { code: 'LRD', flag: '🇱🇷', name: 'Liberian Dollar' },
    { code: 'MGA', flag: '🇲🇬', name: 'Malagasy Ariary' },
    { code: 'MRU', flag: '🇲🇷', name: 'Mauritanian Ouguiya' },
    { code: 'RWF', flag: '🇷🇼', name: 'Rwandan Franc' },
    { code: 'STN', flag: '🇸🇹', name: 'São Tomé & Príncipe Dobra' },
    { code: 'SOS', flag: '🇸🇴', name: 'Somali Shilling' },
    { code: 'SLL', flag: '🇸🇱', name: 'Sierra Leonean Leone' },
    { code: 'SSP', flag: '🇸🇸', name: 'South Sudanese Pound' },
    { code: 'SDG', flag: '🇸🇩', name: 'Sudanese Pound' },
    { code: 'SYP', flag: '🇸🇾', name: 'Syrian Pound' },
    { code: 'IQD', flag: '🇮🇶', name: 'Iraqi Dinar' },
    { code: 'YER', flag: '🇾🇪', name: 'Yemeni Rial' },
    { code: 'AFN', flag: '🇦🇫', name: 'Afghan Afghani' },
    { code: 'TJS', flag: '🇹🇯', name: 'Tajikistani Somoni' },
    { code: 'TMT', flag: '🇹🇲', name: 'Turkmenistani Manat' },
    { code: 'BTN', flag: '🇧🇹', name: 'Bhutanese Ngultrum' },
    { code: 'TOP', flag: '🇹🇴', name: 'Tongan Paʻanga' },
    { code: 'SBD', flag: '🇸🇧', name: 'Solomon Islands Dollar' },
    { code: 'CUC', flag: '🇨🇺', name: 'Cuban Convertible Peso' },
    { code: 'CUP', flag: '🇨🇺', name: 'Cuban Peso' },
    { code: 'GIP', flag: '🇬🇮', name: 'Gibraltar Pound' },
    { code: 'FKP', flag: '🇫🇰', name: 'Falkland Islands Pound' },
    { code: 'BIF', flag: '🇧🇮', name: 'Burundian Franc' },
    { code: 'ERN', flag: '🇪🇷', name: 'Eritrean Nakfa' },
    { code: 'GMD', flag: '🇬🇲', name: 'Gambian Dalasi' },
    { code: 'HRK', flag: '🇭🇷', name: 'Croatian Kuna' },
    { code: 'IRR', flag: '🇮🇷', name: 'Iranian Rial' },
    { code: 'KGS', flag: '🇰🇬', name: 'Kyrgyzstani Som' },
    { code: 'KPW', flag: '🇰🇵', name: 'North Korean Won' },
    { code: 'LBP', flag: '🇱🇧', name: 'Lebanese Pound' },
    { code: 'LYD', flag: '🇱🇾', name: 'Libyan Dinar' },
    { code: 'MZN', flag: '🇲🇿', name: 'Mozambican Metical' },
    { code: 'RUB', flag: '🇷🇺', name: 'Russian Ruble' }
];

